version: '3'

services:
  postgres:
    image: postgres
    container_name: choosely-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: main
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - main-net

  redis:
    image: redis
    container_name: choosely-redis
    ports:
      - 6379:6379

  app:
    build: 
      context: .
      dockerfile: Dockerfile
    container_name: choosely-app
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - main-net
    command: /app/server
    
volumes:
  db-data:

networks:
  main-net:
    driver: bridge
